In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data_file=pd.read_csv("Data.csv")
x=data_file.iloc[:,:-1].values
y=data_file.iloc[:,-1].values

In [3]:
from sklearn.impute import SimpleImputer
tr=SimpleImputer(missing_values=np.nan,strategy='mean')
x[:,1:3]=tr.fit_transform(x[:,1:3])

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ans=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder="passthrough")
x=np.array(ans.fit_transform(x))

In [5]:
from sklearn.preprocessing import LabelEncoder
n=LabelEncoder()
y=n.fit_transform(y)

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=2)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[1.0 0.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]]
[[0.0 1.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 0.0 27.0 48000.0]]
[1 0 1 0 0 0 1 0]
[1 1]


In [8]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)
from sklearn.preprocessing import normalize
x_train[:,4:6]=normalize(x_train[:,4:])
print(x_train)

[[1.0 0.0 0.0 0.0 0.0006034481659893079 0.9999998179251389]
 [1.0 0.0 0.0 0.0 0.0006111109969993461 0.9999998132716572]
 [1.0 0.0 0.0 0.0 0.0006075948245554922 0.9999998154142477]
 [0.0 1.0 0.0 0.0 0.0005555554698216934 0.9999998456790481]
 [0.0 0.0 1.0 0.0 0.000622950698798613 0.9999998059661946]
 [0.0 0.0 0.0 1.0 0.0007457262883743449 0.9999997219461129]
 [1.0 0.0 0.0 0.0 0.0005522387217626696 0.9999998475161855]
 [0.0 1.0 0.0 0.0 0.000602409529247809 0.999999818551363]]


In [9]:
x_test[:,4:]=normalize(x_test[:,4:])
print(x_test)

[[0.0 1.0 0.0 0.0 0.0006271775769977084 0.9999998033241241]
 [0.0 0.0 1.0 0.0 0.0005624999110107633 0.9999998417969126]]
